name: Epicraft
version: 1.7.4
author: Sebastian Wolf
description: Plugin fuer EpiCraft
main: de.wolfsline.Epicraft.Epicraft
softdepend: [WorldGuard]
load: startup
database: true

commands:
  spawn:
    description: Teleportiert dich zum Spawn
    usage: /spawn
    permission: epicraft.spawn
    
  gs:
    description: Kaufe und Verwalte dein Grundstueck
    usage: /gs neu <Name>, + <x> <y>, help
    permissions: 
     - epicraft.gs
  restart:
    description: Startet den Server neu
    usage: /restart
    permissions: 
     - epicraft.restart

  sign:
    description: Ermöglicht dir das automatische Beschriften deiner Schilder an der Grundstücksgrenze
    usgage: /sign
    permissions:
     - epicraft.gs.sign

  fragebogen:
    description: Fragebogeneinstellungen
    usage: /fragebogen

  warn:
    description: Benutzerverwaltung
    usage: /warn

  kick:
    description: Kickt einen Spieler vom Server
    usage: /kick <spieler> <Grund>

  ban:
    description: Bannt einen Spieler vom Server
    usage: /ban <spieler> <Grund>

  home:
    description: Homepunktsystem
    aliases: [sethome, listhome, delhome, rehome]
    usage: /home, sethome <name>
    permissions:
      - epicraft.home.one
      - epicraft.home.multiple

  hide:
    description: Macht dich unsichtbar, bzw. sichtbar
    aliases: [unhide]
    usage: /hide, unhide
    permissions:
      - epicraft.hide
      
  invsee:
    descripton: Zeigt den Inventarinhalt eines Spielers
    usage: /invsee <spieler>
    permissions:
      - epicraft.inv

  lightning:
    description: Blitzt einen Spieler
    usage: /lightning <spieler>
    permissions:
      - epicraft.lightning

  gun:
    description: Neue Gun ja nein
    usage: /gun
    permissions:
     - epicraft.gun

  grenade:
    description: Platziert TNT
    usage: /grenade
    permissions:
     - epicraft.grenade
 
  ensee:
    descripton: Zeigt den Enderchestinhalt eines Spielers
    usage: /ensee <spieler>
    permissions:
      - epicraft.enderchest

  jail:
    description: Gefängnissystem
    aliases: [setjail, tpjail, unjail, setObsi]
    usage: /jail <spieler>
    permissions:
      - epicraft.jail.use
      - epicraft.jail.info
      - epicraft.jail.create

  chat:
    descripton: Chatnachricht erzwingen
    usage: /chat <spieler>

  head:
    descripton: Setze Helm
    usage: /head 
    permissions: epicraft.head

  login:
    descripton: Registrieren und Einloggen
    usage: /login <passwort>, register <passwort> <passwort>
    aliases: [l, email, register, cp, changepw]
    permissions: epicraft.auth

  w:
    description: Flüstert eine Nachricht
    aliases: [w,r,a, msg]
    usage: /w <Spieler> <Nachticht>
    permissions: epicraft.chat.whisper

  support:
    description: Wechselt dein Inventar
    aliases: [sp]
    usage: /support, sp
    permissions:
     - epicraft.inv.switch

  onlinetime:
    description: Zeigt die Spielzeit an
    aliases: [ot]
    usage: /onlinetime
    permissions:
     - epicraft.time

  pvp:
    description: PVP aktivieren, deaktivieren
    usage: /pvp
    permissions:
     - epicraft.pvp

  fly:
    description: Aktiviert fliegen
    usage: /fly [speed]
    permissions:
     - epicraft.fly

  info:
    description: Informationen zum Server
    aliases: [ts3, teamspeak, ts]
    usage: /info

  debug:
    description: ServiceModus
    usage: /debug

  settings:
    description: Einstellungen
    aliases: [set, einst, einstellungen]
    usage: /settings

  me:
    description: Wichtige Nachricht
    usage: /me <msg>
    permissions:
      - epicraft.important

  tp:
    description: Teleport
    usage: /tp
    permissions:
      - epicraft.teleport

  secure:
    description: Verschlüsselt Kisten und Oefen
    usage: /secure
    permissions:
      - epicraft.blocksecure

  horse:
    description: Legt den Besitzer eines Maultieres fest
    usage: /horse <Spieler>
    permissions:
      - epicraft.horse

  api:
    description: Zugriff auf die EventAPI von Epicraft
    usage: /api

  epicraft:
    description: zu DEBUGzwecken
    usage: /epicraft

  uhr:
    description: Die Zeit
    usage: /uhr

  vote:
    description: Vote fuer Epicraft
    usage: /vote

  block:
    description: Werde zum Block
    usage: /block

  chest:
    description: Zugriff auf Kisten in der Ferne
    usage: /chest
    permissions: epicraft.chest

  whois:
    description: Informationen ueber den Spieler
    usage: /whois
    permissions: epicraft.whois

  channel:
    description: Channel im Chat wechseln
    usage: /channel
    permissions: epicraft.chat.channel

  permission:
    description: Verwaltung der Rechte der Spieler
    aliases: [p, per, perm]
    usage: /permission [set] [Spieler] [Gruppe]
    permissions: epicraft.permission.use

  disco:
   description: Für den Discoboden

  ticket:
    description: Hier kannst du Probleme an das Team melden
    usage: /ticket <Nachricht>
    permissions: epicraft.ticket

  welt:
    description: Welten wechseln
    usage: /welt
    permissions:
      - epicraft.world.change
      - epicraft.world.change.other
      - epicraft.world.sign
      - epicraft.world.sign.create

  afk:
    description: AFK Befehl
    usage: /afk
    permissions: epicraft.afk

  back:
    description: Teleportiert dich zu deinem Todespunkt zurück
    usage: /back
    permission: epicraft.tp.back

  microblock:
    description: Setzt einen Microblock
    aliases: [mb, skull]
    usage: /microblock, skull <name>
    permissions:
      - epicraft.micro.block
      - epicraft.micro.skull

permissions:
  epicraft.*:
    description: Alle Rechte fuer Epicraft
    children:
      epicraft.chest: true
      epicraft.enderchest: true
      epicraft.fly: true
      epicraft.inv: true
      epicraft.jail: true
      epicraft.restart: true
      epicraft.spawn: true
      epicraft.spawn.set: true
      epicraft.teleport: true
      epicraft.time: true
      epicraft.hide: true
      epicraft.whois: true
      epicraft.api: true
      epicraft.gun: true
      epicraft.head: true
      epicraft.lightning: true
      epicraft.pvp: true
      epicraft.grenade: true
      epicraft.gs: true
      epicraft.gs.sign: true
      epicraft.chat: true
      epicraft.chat.channel: true
      epicraft.chat.whisper: true
      epicraft.chat.color: true
      epicraft.chat.fake: true
      epicraft.sign.color: true
      epicraft.command.allow: true
      epicraft.important: true
      epicraft.auth: true
      epicraft.blocksecure: true
      epicraft.horse: true
      epicraft.ticket: true
      epicraft.warn: true
      epicraft.ban: true
      epicraft.kick: true
      epicraft.world.change: true
      epicraft.world.change.other: true
      epicraft.world.sign: true
      epicraft.world.sign.create: true
      epicraft.world.load: true
      epicraft.world.unload: true
      epicraft.world.create: true
      epicraft.egg.catch: true
      epicraft.home.one: true
      epicraft.home.multiple: true
      epicraft.afk: true
      epicraft.ticket.team: true
      epicraft.sign.lift.create: true
      epicraft.sign.lift: true
      epicraft.blocksecure.team: true
      epicraft.horse.team: true
      epicraft.fragebogen: true
      epicraft.gs.team: true
      epicraft.wartung: true
      epicraft.door.access: true
      epicraft.micro.block: true
      epicraft.micro.skull: true