name: Epicraft
version: 1.7.4
author: Sebastian Wolf
description: Plugin fuer EpiCraft
main: de.wolfsline.Epicraft.Epicraft
softdepend: [MultiVerse, multiverse-core, Vault, WorldGuard, Votifier]
load: startup
database: true

commands:
  spawn:
    description: Teleportiert dich zum Spawn
    usage: /spawn
    permission: epicraft.spawn.use
    
  gs:
    description: Kaufe und Verwalte dein Grundstueck
    usage: /gs neu <Name>, + <x> <y>, help
    permissions: 
     - epicraft.gs.use
     - epicraft.gs.remove
     - epicraft.gs.warp

  restart:
    description: Startet den Server neu
    usage: /restart
    permissions: 
     - epicraft.restart.use

  sign:
    description: Ermöglicht dir das automatische Beschriften deiner Schilder an der Grundstücksgrenze
    usgage: /sign
    permissions:
     - epicraft.gs.sign
     - epicraft.sign.mod
     - epicraft.sign.guard
     - epicraft.register.gast

  ep:
    description: Server einstellungen
    usage: /ep
    permissions:
     - epicraft.ep.use

  warn:
    description: Benutzerverwaltung
    usage: /warn
    permissions:
      - epicraft.restriction.use
  kick:
    description: Kickt einen Spieler vom Server
    usage: /kick <spieler> <Grund>
    permissions:
      - epictraft.restriction.team
  ban:
    description: Bannt einen Spieler vom Server
    usage: /ban <spieler> <Grund>
    permissions:
      - epicraft.restriction.team.ban

  home:
    description: Homepunktsystem
    aliases: [sethome, listhome, delhome, rehome]
    usage: /home, sethome <name>
    permissions:
      - epicraft.home.one
      - epicraft.home.multiple

  hide:
    description: Macht dich unsichtbar, bzw. sichtbar
    aliases: [unhide]
    usage: /hide, unhide
    permissions:
      - epicraft.hide.use
      
  invsee:
    descripton: Zeigt den Inventarinhalt eines Spielers
    usage: /invsee <spieler>
    permissions:
      - epicraft.inv.use

  lightning:
    description: Blitzt einen Spieler
    usage: /lightning <spieler>
    permissions:
      - epicraft.lightning.use

  gun:
    description: Neue Gun ja nein
    usage: /gun
    permissions:
     - epicraft.gun.create

  grenade:
    description: Platziert TNT
    usage: /grenade
    permissions:
     - epicraft.greande.use
 
  ensee:
    descripton: Zeigt den Enderchestinhalt eines Spielers
    usage: /ensee <spieler>
    permissions:
      - epicraft.enderchest.use

  jail:
    description: Gefängnissystem
    aliases: [setjail, tpjail, unjail, setObsi]
    usage: /jail <spieler>
    permissions:
      - epicraft.jail.use
      - epicraft.jail.info
      - epicraft.jail.create

  chat:
    descripton: Chatnachricht erzwingen
    usage: /chat <spieler>

  head:
    descripton: Setze Helm
    usage: /head 

  login:
    descripton: Registrieren und Einloggen
    usage: /login <passwort>, register <passwort> <passwort>
    aliases: [l, email, register, cp, changepw]

  w:
    description: Flüstert eine Nachricht
    aliases: [w,r,a, msg]
    usage: /w <Spieler> <Nachticht>

  support:
    description: Wechselt dein Inventar
    aliases: [sp]
    usage: /support, sp
    permissions:
     - epicraft.inv.switch

  onlinetime:
    description: Zeigt die Spielzeit an
    aliases: [ot]
    usage: /onlinetime
    permissions:
     - epicraft.time.look

#  map:
#    description: Map
#    usage: /map

  pvp:
    description: PVP aktivieren, deaktivieren
    usage: /pvp
    permissions:
     - epicraft.pvp.use

  fly:
    description: Aktiviert fliegen
    usage: /fly [speed]
    permissions:
     - epicraft.fly.use

  info:
    description: Informationen zum Server
    aliases: [ts3, teamspeak, ts]
    usage: /info

  debug:
    description: ServiceModus
    usage: /debug

  settings:
    description: Einstellungen
    aliases: [set, einst, einstellungen]
    usage: /settings

  me:
    description: Wichtige Nachricht
    usage: /me <msg>
    permissions:
      - epicraft.important

  tp:
    description: Teleport
    aliases: [back]
    usage: /tp
    permissions:
      - epicraft.teleport

  secure:
    description: Verschlüsselt Kisten und Oefen
    usage: /secure
    permissions:
      - epicraft.blocksecure.use

  horse:
    description: Legt den Besitzer eines Maultieres fest
    usage: /horse <Spieler>
    permissions:
      - epicraft.horse.setowner

  api:
    description: Zugriff auf die EventAPI von Epicraft
    usage: /api

  epicraft:
    description: zu DEBUGzwecken
    usage: /epicraft

  system:
    description: Systemzeug
    usage: /system

#  sky:
#    description: Aktiviert fliegen
#    usage: /sky [speed]
#    permissions:
#     - epicraft.sky.create

  jump:
    description: Vectorspass
    usage: /jump

  uhr:
    description: Die Zeit
    usage: /uhr

  skull:
    description: Head
    usage: /skull <name>

  vote:
    description: Vote fuer Epicraft
    usage: /vote

  block:
    description: Werde zum Block
    usage: /block

  chest:
    description: Zugriff auf Kisten in der Ferne
    usage: /chest

  whois:
    description: Informationen ueber den Spieler
    usage: /whois

  channel:
    description: Channel im Chat wechseln
    usage: /channel
    permissions: epicraft.chat.channel

  permission:
    description: Verwaltung der Rechte der Spieler
    aliases: [p, per, perm]
    usage: /permission [set] [Spieler] [Gruppe]
    permissions: epicraft.permission.use

  disco:
   description: Für den Discoboden

permissions:
  epicraft.*:
    description: Alle Rechte fuer Epicraft
    children:
      epicraft.einstellungen.admin: true
      epicraft.whisper.use: true
      epicraft.einstellungen.use: true
      epicraft.me.use: true
      epicraft.permission.use: true
      epicraft.api.use: true
      epicraft.chat.use: true
      epicraft.info.wer: true
      epicraft.chat.channel: true
      epicraft.verwarnung.use: true
      epicraft.verwarnung.team: true
      epicraft.verwarnung.use.ban: true
      epicraft.teleport.use: true